import type { Project } from "@/components/ui/ProjectCard";

// IMAGE PATHS: all point to a dark placeholder until real screenshots are added.
// To replace: create /public/projects/<slug>/ and add cover.jpg + gallery images.
// Then update the `images` array below with the actual paths.

export const PROJECTS: Project[] = [
    {
        id: 1,
        title: "CAJIX",
        description: `Sistema SaaS multi-tenant de gestión financiera para PYMEs. Cada empresa accede a una instancia propia con branding personalizado, doble libro de caja (formal + informal con toggle de privacidad), módulo de turnos con URL pública de auto-booking, y panel de superadmin para gestión de clientes y MRR.\n\nStack bleeding-edge: Next.js 16, React 19, TypeScript, Supabase SSR con Row Level Security en PostgreSQL, Tailwind v4. Autenticación por Supabase SSR con middleware de protección de rutas. Exportación de balance a PDF para contadores con jsPDF. Dashboard financiero con Recharts. Live en cajix.site.`,
        project_type: "web",
        tags: ["Next.js 16", "React 19", "SaaS", "Supabase", "TypeScript", "Multi-tenant"],
        images: ["/projects/placeholder.jpg"],
        demo_link: "https://cajix.site",
        repo_link: "https://github.com/Luguin8/saas-backoffice",
    },
    {
        id: 2,
        title: "Lil PDF",
        description: `Herramienta de escritorio 100% offline para fusionar, dividir y reorganizar visualmente archivos PDF. Instalador menor a 10 MB, cero dependencias externas, cero envío de datos a servidores.\n\nBackend en Rust con la crate lopdf para manipulación binaria del árbol de páginas, garantizando compatibilidad total con Adobe Acrobat. Frontend en React con pdfjs-dist y carga progresiva por lazy loading: documentos de 1.000 páginas sin freezing. Drag-and-drop desde el sistema operativo via Tauri.onDragDropEvent. Features: merge multi-archivo con reorder, split por rango o en chunks iguales, organización visual con rotate/delete/reorder por página, historial de undo/redo, preview modal con zoom, y auto-updater integrado. Publicado en GitHub Releases con instalador Windows.`,
        project_type: "desktop",
        tags: ["Rust", "Tauri v2", "React", "PDF", "Desktop", "lopdf"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/lil-pdf",
        download_link: "https://github.com/Luguin8/lil-pdf/releases/latest",
    },
    {
        id: 3,
        title: "LectorApp · Florecillas",
        description: `App de lectura espiritual publicada en Google Play Store (100+ descargas). Textos de dominio público, narración por Text-to-Speech, tema día/noche, marcadores y todas las preferencias persistidas entre sesiones.\n\nAlgoritmo propio de chunking TTS que fragmenta capítulos en segmentos menores a 3.000 caracteres para sortear el límite de la Speech API nativa, ejecutando la narración en callbacks encadenados sin cortar palabras. Catálogo de libros desacoplado del código via biblioteca.json — agregar un título nuevo requiere cero cambios de pantalla. Responsive para tablets (grid 2 columnas, modales centrados en landscape). Monetización con AdMob (Banner + Medium Rectangle) con silent fail-safe. Stack: React Native 0.81, Expo SDK 54, expo-speech, EAS Build + EAS Submit. Package: com.juliana.florecillas.`,
        project_type: "mobile",
        tags: ["React Native", "Expo", "Google Play", "TTS", "AdMob", "EAS"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/LectorApp",
        download_link: "https://play.google.com/store/apps/details?id=com.juliana.florecillas",
    },
    {
        id: 4,
        title: "AirwiLens",
        description: `Convierte cualquier Android o iOS en una webcam profesional de 720p/24fps sobre red Wi-Fi local, inyectable en Zoom, Google Meet y OBS como cámara virtual.\n\nSistema de dos partes: cliente React Native con Vision Camera v4 ejecutando Frame Processors en threads C++ nativos via VisionCameraProxy (sin pasar por el bridge de JS), y servidor Python con GUI Tkinter que decodifica frames, los procesa con OpenCV y los inyecta como cámara virtual via pyvirtualcam. Frames transmitidos como JPEG/Base64 por WebSocket con single-slot queue y dropping inteligente (~100–200ms de latencia en LAN). Protocolo bidireccional: el servidor envía comandos (flash, flip, modo mute, zoom) al móvil en tiempo real. Telemetría de batería cada 10 segundos. Modo ahorro energético en mobile durante sesiones largas.`,
        project_type: "mobile",
        tags: ["React Native", "Vision Camera", "Python", "OpenCV", "WebSocket", "C++"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/WebcamPro",
    },
    {
        id: 5,
        title: "PlugToSell",
        description: `Suite de 6 micro-widgets JavaScript inyectables vía Google Tag Manager en tiendas TiendaNube y Shopify para aumentar la conversión, sin modificar el tema.\n\nCada widget activa una palanca de psicología de compra: barra de progreso hacia envío gratis (spy de fetch en TiendaNube, polling REST en Shopify), badge de best-seller con overlay dorado, badge de trending con urgencia, alerta de stock bajo, trust badges (pago seguro, envío nacional), y pop-up de keep-browsing por exit-intent con productos vistos recientemente. Todos los eventos rastreados via GA4 a través del pipeline de tags y triggers de GTM. Migración completa Shopify → TiendaNube documentada, con herramientas de reverse-engineering propias para descubrir los endpoints y la estructura de window.LS.`,
        project_type: "web",
        tags: ["Vanilla JS", "GTM", "Shopify", "TiendaNube", "GA4", "E-commerce"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/PlugToSell",
    },
    {
        id: 6,
        title: "Slot Math Model",
        description: `Suite completa de certificación matemática para una slot machine de 5 rodillos, entregable profesional para cliente del sector gambling.\n\nRTP teórico calibrado al 96.17% mediante cálculo combinatorio. Sistema de 3 jackpots independientes (Mini / Minor / Major) con semillas de casino y contribución controlada al 6.00%. Simulación Monte Carlo de 150 sesiones con semillas variables (RTP simulado ~96.85%; delta de +0.7% documentado y justificado por aporte de semillas). Generación automática de Parsheet en Excel (.xlsx) con todas las fórmulas de combinatoria y EV de Free Spins incrustadas para revisión de auditoría externa. Cualquier sesión es 100% reproducible y auditable via python simulation.py --verify [SEED].`,
        project_type: "desktop",
        tags: ["Python", "Casino Math", "Monte Carlo", "Excel", "RTP", "Gambling"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/SlotsPython",
    },
    {
        id: 7,
        title: "AppSheet Silos",
        description: `Sistema de gestión de depósitos agrícolas para cliente industrial, 500.000+ kg de capacidad operativa. Construido en AppSheet con Google Sheets como backend.\n\nArquitectura event-driven: Alert Bots para notificaciones automáticas, Scheduled Bots para reportes periódicos por email. Algoritmo propietario de generación de códigos de lote con control de colisiones. Búsqueda híbrida bidireccional (por número de lote O por código de producto). Data Actions encadenadas para operaciones de alta complejidad (ingresos, egresos, ajustes de inventario). Cero código escrito, funcionalidad operativa real en producción.`,
        project_type: "web",
        tags: ["AppSheet", "Google Sheets", "No-Code", "Automatización", "Bots"],
        images: ["/projects/placeholder.jpg"],
    },
    {
        id: 8,
        title: "GYMORA",
        description: `Aplicación de escritorio nativa, offline y de alto rendimiento para control de accesos y gestión de pagos de un gimnasio. Sistema de licencias por huella de hardware.\n\nCore en Rust con rusqlite en WAL mode para concurrencia segura. Frontend React "tonto" que solo dispara comandos Tauri. Kiosco de acceso: global keyboard listener captura el DNI sin input enfocado — respuesta visual pantalla completa durante 3 segundos (verde/rojo). Auth por PIN con roles Dueño / Profesor. Licencia bloqueada al hardware: hash combinado de Motherboard UUID + CPU ID + MAC Address. Módulos: ABM de alumnos, cobro de cuotas, registro de asistencias, y generación de reportes PDF desde Rust via genpdf. Auto-updater con @tauri-apps/plugin-updater.`,
        project_type: "desktop",
        tags: ["Rust", "Tauri v2", "React", "SQLite", "Desktop", "Hardware-Lock"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/Gymora",
    },
    {
        id: 9,
        title: "CVdeador",
        description: `Herramienta de escritorio con LLM integrado para generar CVs HTML optimizados para ATS, adaptados automáticamente a cada oferta de trabajo.\n\nFlujo: el usuario sube su CV base (PDF/imagen) → la IA extrae el contenido estructurado → el usuario sube la descripción del puesto → la IA genera un CV ATS-optimizado en HTML puro sin markdown. Stack: Rust + Tauri v2 + React + TypeScript + Tailwind v4. API key configurable por el usuario (no bundleada en el binario). Template de CV personalizable por el usuario. Prompt chain de dos pasos: extracción primero, generación semántica después. Dropzones con drag-and-drop nativo via Tauri.`,
        project_type: "desktop",
        tags: ["Rust", "Tauri v2", "React", "LLM", "IA", "ATS"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/CVdeador",
    },
    {
        id: 10,
        title: "GolLog",
        description: `Plataforma web full-stack para calificar partidos de fútbol. API REST completa en Django REST Framework con datos reales de TheSportsDB. SPA en Vue 3.\n\nBackend con ViewSets, Serializers y DRF router. Modelos relacionales: Liga, Equipo, Partido, Calificación, Perfil de usuario. Comando de management personalizado para importar datos reales desde la API externa. Bundled data.json para seeding offline. Django admin para gestión backend. Frontend Vue 3: listado de ligas, equipos por liga, calendario de partidos y envío de calificaciones de usuarios autenticados. PostgreSQL como base de datos principal.`,
        project_type: "web",
        tags: ["Django", "DRF", "Vue 3", "PostgreSQL", "REST API", "Python"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/GolLog",
    },
    {
        id: 11,
        title: "DCA King",
        description: `Ecosistema completo de tres repositorios para automatizar y monitorear trading por Dollar Cost Averaging en criptomonedas.\n\nInterfazDCA: panel admin FastAPI + Jinja2 SSR para monitoreo de grupos de bots y órdenes de seguridad (SOs). DashboardDCA: backend FastAPI con SQLModel + SQLite que ingiere webhooks de TradingView, expone REST API y sirve dashboard híbrido SSR/API; modelos Pydantic con StringConstraints y enums tipados para timeframes y comportamientos de apertura/cierre. ComponenteBots: widget Vanilla JS embebible con estilos CSS aislados que visualiza estrategias DCA en dashboards externos sin dependencias de framework.`,
        project_type: "web",
        tags: ["FastAPI", "Python", "SQLModel", "Vanilla JS", "DCA", "Crypto"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/DashboardDCA",
    },
    {
        id: 12,
        title: "Aberturas Miño",
        description: `E-commerce completo para una carpintería y maderera, con UX simplificada orientada a clientes adultos con baja alfabetización digital.\n\nSPA React + Vite conectada a Supabase (Auth + Postgres). Catálogo por categorías, detalle de producto, carrito, checkout, y página de métodos de pago y FAQ. Panel admin protegido via ProtectedRoute + AuthContext con sesión de Supabase: CRUD de productos con imágenes, gestión de pedidos. Feedback de acciones via react-hot-toast. Decisiones de UX orientadas explícitamente al perfil del cliente objetivo: tipografías grandes, navegación directa, flujos sin ambigüedad.`,
        project_type: "web",
        tags: ["React", "Vite", "Supabase", "E-commerce", "TypeScript"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/aberturasmino",
    },
    {
        id: 13,
        title: "AppPers",
        description: `App personal all-in-one en React Native con tres módulos: rastreo automático de asistencia al gimnasio por geofencing, cronómetro adaptativo al clima, y tracker de precios de supermercados.\n\nEl módulo de gimnasio corre un Foreground Service en background en Android, sondea la geolocalización cada hora en radio de 100m, detecta 2 horas consecutivas de presencia y avanza el ciclo de rutina automáticamente sin interacción del usuario. El cronómetro consulta OpenWeatherMap y adapta el tiempo de cuenta regresiva a la temperatura real (24 min a ≤20°C, 16 min a >27°C). SQLite Singleton con Promise Guard para prevenir race conditions de inicialización concurrente. New Architecture habilitada (Fabric renderer + Turbo Modules).`,
        project_type: "mobile",
        tags: ["React Native", "Expo", "SQLite", "Geofencing", "Background Tasks", "OpenWeatherMap"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/AppPers",
    },
    {
        id: 14,
        title: "Comida Callejera",
        description: `App móvil para descubrir puestos de comida callejera en un mapa interactivo, con reseñas de usuarios y gestión por parte de los dueños de cada puesto.\n\nMapView con marcadores, filtro por abiertos/cerrados, detalle de puesto y pantalla de reseñas. Autenticación dual: usuarios regulares y dueños de puestos con rutas diferenciadas. Datos en tiempo real desde Firebase Firestore. Auth con Firebase. Geolocalización del usuario via expo-location. Listener en tiempo real de onAuthStateChanged para actualizar la vista según el estado de sesión. Stack: React Native + Expo + Firebase + react-native-maps + React Navigation.`,
        project_type: "mobile",
        tags: ["React Native", "Firebase", "Google Maps", "Expo", "Firestore"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/comidaCallejera",
    },
    {
        id: 15,
        title: "Burger House",
        description: `Aplicación web de comida rápida full-stack con REST API backend, catálogo de productos, carrito, personalización de hamburguesas y panel de administración.\n\nFrontend Vanilla JS consumiendo REST API en runtime (sin localStorage para datos de negocio). Backend Node.js + Express + SQLite con JWT. Rutas separadas para productos, pedidos y auth. Panel admin: CRUD de productos con upload de imágenes y gestión de pedidos. Diseño responsive con tema oscuro. Todo el código documentado exhaustivamente en español con comentarios inline explicando la lógica y las decisiones de diseño.`,
        project_type: "web",
        tags: ["Node.js", "Express", "SQLite", "REST API", "Vanilla JS", "JWT"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/BurgerHouse",
    },
    {
        id: 16,
        title: "AppCC",
        description: `App móvil privada para parejas: mensajería de forma larga, alertas hápticas y espacio compartido de música.\n\nEspacios vinculados por código de conversación único (exactamente dos usuarios). Mensajes con mínimo de 150 caracteres obligatorio, forzando comunicación reflexiva. Función "Molestar": envía patrones de vibración háptica (corta, intermitente o constante) al compañero. Historial compartido de links de Spotify. Fondo de chat personalizable desde la galería del dispositivo. Exportación del historial a PDF via dart/pdf. Vista "Chismosear": accede a la canción, fondo y timestamp del último poke del compañero. Stack: Flutter + Dart + SharedPreferences + image_picker + path_provider.`,
        project_type: "mobile",
        tags: ["Flutter", "Dart", "Mobile", "SharedPreferences", "PDF"],
        images: ["/projects/placeholder.jpg"],
        repo_link: "https://github.com/Luguin8/AppCC_Android",
    },
];
